version: '3.8'

services:
  # 1. Parça: Veritabanı (PostgreSQL)
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234*"
      POSTGRES_DB: hash_db
    ports:
      - "5432:5432"

  # 2. Parça: Önbellek (Redis)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 3. Parça:FastAPI Uygulaması (hash analizi ile)
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
